theme: jekyll-theme-minimal
title: [Saumya Kapila's Data-310 Public Repository]
description: [This will house all my public assignments for the Data-310 Class]
logo: [Data310-Public/etienne-girardet-360034-unsplash.jpg]
